<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.29.1" />
    <PackageReference Include="Azure.Identity" Version="1.13.2" Aliases="identity" />
    <PackageReference Include="Azure.ResourceManager" Version="1.14.0" />
    <PackageReference Include="Azure.ResourceManager.Resources" Version="1.11.0" />
    <PackageReference Include="Azure.ResourceManager.Storage" Version="1.4.4" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.11" />
  </ItemGroup>

</Project>
